# Generated by Django 4.2.1 on 2023-06-06 11:03

from django.db import migrations, models
import select_file.models


class Migration(migrations.Migration):
    dependencies = [
        ("select_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvfile",
            name="file",
            field=models.FileField(upload_to=select_file.models.csv_file_path),
        ),
    ]
